// Generated by CoffeeScript 1.9.3
(function() {
  var StormData, StormRegistry, Test, TestData, TestManager, TestRegistry, assert, async, extend, ping, request, util,
    extend1 = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  assert = require('assert');

  StormRegistry = require('stormregistry');

  StormData = require('stormdata');

  util = require('util');

  request = require('request-json');

  extend = require('util')._extend;

  async = require('async');

  ping = require('./pingdriver');

  TestRegistry = (function(superClass) {
    extend1(TestRegistry, superClass);

    function TestRegistry(filename) {
      this.on('load', function(key, val) {
        var entry;
        entry = new TestData(key, val);
        if (entry != null) {
          entry.saved = true;
          return this.add(entry);
        }
      });
      this.on('removed', function(entry) {
        if (entry.destructor != null) {
          return entry.destructor();
        }
      });
      TestRegistry.__super__.constructor.call(this, filename);
    }

    TestRegistry.prototype.add = function(data) {
      var entry;
      if (!(data instanceof TestData)) {
        return;
      }
      return entry = TestRegistry.__super__.add.call(this, data.id, data);
    };

    TestRegistry.prototype.update = function(data) {
      return TestRegistry.__super__.update.call(this, data.id, data);
    };

    TestRegistry.prototype.get = function(key) {
      var entry;
      entry = TestRegistry.__super__.get.call(this, key);
      if (entry == null) {
        return;
      }
      if ((entry.data != null) && entry.data instanceof TestData) {
        entry.data.id = entry.id;
        return entry.data;
      } else {
        return entry;
      }
    };

    return TestRegistry;

  })(StormRegistry);

  TestData = (function(superClass) {
    var TestSchema;

    extend1(TestData, superClass);

    TestSchema = {
      name: "Test",
      type: "object",
      properties: {
        name: {
          type: "string",
          required: false
        },
        destination: {
          type: "string",
          required: true
        },
        type: {
          type: "string",
          required: true
        },
        duration: {
          type: "string",
          required: false
        },
        config: {
          type: "object",
          required: false
        }
      }
    };

    function TestData(id, data) {
      TestData.__super__.constructor.call(this, id, data, TestSchema);
    }

    return TestData;

  })(StormData);


  /*
  config = 
      destination:
      config :
          adpative: yes
          flood : yes
          count : 20
          packetsize : 1400
          interval : 23
  
  
  
  -c  <count>
  -A  adpative ping --- kind of flood
  -s  <package size>
  -f   flood ping 
  -q   quite mode -- only summary output
   */

  Test = (function() {
    function Test() {
      this.testData = {};
      this.testResult = [];
      util.log("New Test is created" + JSON.stringify(this.testData));
    }

    Test.prototype.CreatePingCommand = function() {
      var Basecommand, flags;
      Basecommand = "ping";
      if (this.testData.config.flood === "yes") {
        flags = "-f ";
      } else if (this.testData.config.adaptive === "yes") {
        flags = " -A ";
      } else {
        flags = " ";
      }
      if (this.testData.config.count != null) {
        flags += " -c " + this.testData.config.count;
      }
      if (this.testData.config.packetsize != null) {
        flags += " -s " + this.testData.config.packetsize;
      }
      flags += " -q ";
      this.pingcommand = Basecommand + flags + this.testData.destination;
      return console.log("ping comands is " + this.pingcommand);
    };

    Test.prototype.create = function(tdata) {
      this.testData = extend({}, tdata.data);
      this.testData.createdTime = new Date;
      this.uuid = tdata.id;
      util.log("Test created with " + JSON.stringify(this.testData));
      util.log(this.testData.type);
      if (this.testData.type === "ping") {
        util.log(this.testData.type);
        return this.CreatePingCommand(this.testData.config);
      }
    };

    Test.prototype.run = function() {
      this.testData.startedTime = new Date;
      return ping.runping(this.pingcommand, (function(_this) {
        return function(result) {
          _this.testData.completedTime = new Date;
          console.log("ping result is " + result);
          _this.testResult = result;
          return _this.testData.testResult = _this.testResult;
        };
      })(this));
    };

    Test.prototype.get = function() {
      return this.testData;
    };

    Test.prototype.del = function() {
      return true;
    };

    return Test;

  })();

  TestManager = (function() {
    function TestManager() {
      this.registry = new TestRegistry;
      this.testObjs = {};
    }

    TestManager.prototype.create = function(data, callback) {
      var err, testObj, testdata;
      try {
        testdata = new TestData(null, data);
      } catch (_error) {
        err = _error;
        console.log("TestData - invalid schema " + JSON.stringify(err));
        return callback(new Error("Invalid Schema Input "));
      } finally {
        console.log("TestData  created " + JSON.stringify(testdata));
      }
      console.log("Test schema check is passed " + JSON.stringify(testdata));
      testObj = new Test;
      testObj.create(testdata);
      this.testObjs[testObj.uuid] = testObj;
      testObj.run();
      return callback(this.registry.add(testdata));
    };

    TestManager.prototype.del = function(id, callback) {
      var obj, result;
      obj = this.testObjs[id];
      if (obj != null) {
        this.registry.remove(obj.uuid);
        result = obj.del();
        return callback(result);
      } else {
        return callback(new Error("Unknown Test ID"));
      }
    };

    TestManager.prototype.get = function(id, callback) {
      var obj;
      obj = this.testObjs[id];
      if (obj != null) {
        return callback(obj.get());
      } else {
        return callback(new Error("Unknown Test ID"));
      }
    };

    TestManager.prototype.list = function(callback) {
      return callback(this.registry.list());
    };

    return TestManager;

  })();

  module.exports = new TestManager;

}).call(this);
