// Generated by CoffeeScript 1.9.3
(function() {
  var exec, testrunner, util;

  util = require('util');

  exec = require('child_process').exec;

  testrunner = (function() {
    function testrunner() {}

    testrunner.prototype.execute = function(command, callback) {
      if (command == null) {
        callback(false);
      }
      util.log("executing " + command + "...");
      return exec(command, (function(_this) {
        return function(error, stdout, stderr) {
          util.log("Execution- Error : " + error);
          util.log("Execution - stderr : " + stderr);
          if (error) {
            return callback(error);
          } else {
            return callback(stdout);
          }
        };
      })(this));
    };

    testrunner.prototype.runCommand = function(command, callback) {
      return this.execute(command, (function(_this) {
        return function(result) {
          return callback(result);
        };
      })(this));
    };

    return testrunner;

  })();

  module.exports = new testrunner;

}).call(this);
