// Generated by CoffeeScript 1.9.3
(function() {
  var IPRoute2, Schema, exec, fs, util, validate;

  util = require('util');

  exec = require('child_process').exec;

  fs = require('fs');

  validate = require('json-schema').validate;

  Schema = {
    name: "netem",
    type: "object",
    required: true,
    properties: {
      bandwidth: {
        "type": "string",
        "required": true
      },
      latency: {
        "type": "string",
        "required": true
      },
      jitter: {
        "type": "string",
        "required": true
      },
      pktloss: {
        "type": "string",
        "required": true
      }
    }
  };

  IPRoute2 = (function() {
    function IPRoute2() {}

    IPRoute2.prototype.setDelayLoss = function(ifname, data, callback) {
      var command, correlation, distribution, latency, loss, variation;
      latency = data.latency;
      distribution = "normal";
      variation = data.jitter;
      correlation = "10%";
      loss = data.pktloss;
      correlation = "10%";
      command = "tc qdisc add dev " + ifname + " root handle 1:0  netem delay " + latency + " " + variation + " " + correlation + " distribution " + distribution + " loss " + loss + " " + correlation;
      util.log("netstats executing " + command + "...");
      return exec(command, (function(_this) {
        return function(error, stdout, stderr) {
          if (error != null) {
            util.log("netstats: execute - Error : " + error);
          }
          if (stdout != null) {
            util.log("netstats: execute - stdout : " + stdout);
          }
          if (stderr != null) {
            util.log("netstats: execute - stderr : " + stderr);
          }
          return callback(true);
        };
      })(this));
    };

    IPRoute2.prototype.setBandwidth = function(ifname, data, callback) {
      var avgpkt, bandwidth, command;
      avgpkt = "1000";
      bandwidth = data.bandwidth;
      command = "tc qdisc add dev " + ifname + " parent 1:1 handle 10: tbf rate  " + bandwidth + " buffer 1600 limit 3000";
      util.log("netstats executing " + command + "...");
      return exec(command, (function(_this) {
        return function(error, stdout, stderr) {
          if (error != null) {
            util.log("netstats: execute - Error : " + error);
          }
          if (stdout != null) {
            util.log("netstats: execute - stdout : " + stdout);
          }
          if (stderr != null) {
            util.log("netstats: execute - stderr : " + stderr);
          }
          return callback(true);
        };
      })(this));
    };

    IPRoute2.prototype.setLinkChars = function(ifname, data, callback) {
      var chk;
      util.log(("iproute2drive setlink chars input - " + ifname + "  - ") + JSON.stringify(data));
      chk = validate(data, Schema);
      console.log('validate result ', chk);
      if (!chk.valid) {
        throw new Error("schema check failed" + chk.valid);
        return callback(false);
      }
      callback(true);
      return this.setDelayLoss(ifname, data, (function(_this) {
        return function(result) {
          util.log("setDelay result" + result);
          return _this.setBandwidth(ifname, data, function(result) {
            return util.log("setBandwidth result " + result);
          });
        };
      })(this));
    };

    IPRoute2.prototype.addTapLink = function(ifname1, ifname2, callback) {
      var command;
      command = "ip link delete " + ifname;
      util.log("executing " + command + "...");
      return exec(command, (function(_this) {
        return function(error, stdout, stderr) {
          if (error != null) {
            util.log("link remove: execute - Error : " + error);
          }
          if (stdout != null) {
            util.log("link removal: execute - stdout : " + stdout);
          }
          if (stderr != null) {
            util.log("link removal: execute - stderr : " + stderr);
          }
          if (error == null) {
            callback(true);
          }
          if (error != null) {
            return callback(false);
          }
        };
      })(this));
    };

    IPRoute2.prototype.delLink = function(ifname, callback) {
      var command;
      command = "ip link delete " + ifname;
      util.log("executing " + command + "...");
      return exec(command, (function(_this) {
        return function(error, stdout, stderr) {
          if (error != null) {
            util.log("link remove: execute - Error : " + error);
          }
          if (stdout != null) {
            util.log("link removal: execute - stdout : " + stdout);
          }
          if (stderr != null) {
            util.log("link removal: execute - stderr : " + stderr);
          }
          if (error == null) {
            callback(true);
          }
          if (error != null) {
            return callback(false);
          }
        };
      })(this));
    };

    return IPRoute2;

  })();

  module.exports = new IPRoute2;

}).call(this);
